"""Per-session Docker sandbox runtime manager (S4).

Each Code Console session gets an isolated container running the coding CLI
(codebuddy). The octop process talks to docker.sock to create/destroy these
sandboxes; the ACP runner command is overridden per-session to
``docker exec -i <container> codebuddy --acp`` so the CLI runs inside the
sandbox, not in the octop host container.

Security: the sandbox never receives ``/var/run/docker.sock``.
"""

from __future__ import annotations

import io
import json
import logging
import os
import re
import shlex
import socket
import tarfile
import time
import uuid

import docker
from docker.models.containers import Container

from octop.infra.db.repos.coding_runtimes import RuntimeRepo, RuntimeRow

logger = logging.getLogger(__name__)

DEFAULT_IMAGE = "octop-codebuddy-sandbox:2.162"
DEFAULT_CPUS = 1.0
DEFAULT_MEMORY = "1g"
DEFAULT_PIDS_LIMIT = 200
CONTAINER_PREFIX = "octop-code-"
SANDBOX_WORKDIR = "/workspace"

# Sandbox image per runner. DEFAULT_IMAGE only ships codebuddy, so every other
# runner needs its own image to run isolated. Point at one with
# ``OCTOP_CODE_SANDBOX_IMAGE_<RUNNER>=<image:tag>`` (runner name upper-cased,
# dashes turned into underscores), e.g.::
#
#   OCTOP_CODE_SANDBOX_IMAGE_CLAUDE_CODE=octop-claude-code-sandbox:latest
#
# Runners without an image fall back to DEFAULT_IMAGE and run only if the CLI
# happens to be present there — see ``_probe_missing_command``.
_RUNNER_SANDBOX_IMAGE: dict[str, str] = {
    "codebuddy": "octop-codebuddy-sandbox:2.162",
}
_SANDBOX_IMAGE_ENV_PREFIX = "OCTOP_CODE_SANDBOX_IMAGE_"

# Per-session Codex config (DeepSeek provider). Mirrors codex-config.toml baked
# into the image; the model line is rewritten when a session picks a model.
_CODEX_CONFIG_TMPL = """# Generated by Octop for this coding session.
model = "{model}"
model_provider = "deepseek"
# DeepSeek chat/reasoner both expose a 64K context window; declaring it keeps
# codex from falling back to generic model metadata (and warning about it).
model_context_window = 65536

[model_providers.deepseek]
name = "DeepSeek"
base_url = "https://api.deepseek.com/v1"
wire_api = "responses"
env_key = "DEEPSEEK_API_KEY"
"""

_MODEL_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/\-]{0,63}$")


def _sandbox_image(runner: str | None, image: str | None = None) -> str:
    """Resolve the sandbox image for *runner* (explicit > env > table)."""
    if image:
        return image
    name = (runner or "").strip()
    if name:
        env_key = _SANDBOX_IMAGE_ENV_PREFIX + name.upper().replace("-", "_")
        from_env = (os.environ.get(env_key) or "").strip()
        if from_env:
            return from_env
        if name in _RUNNER_SANDBOX_IMAGE:
            return _RUNNER_SANDBOX_IMAGE[name]
    return DEFAULT_IMAGE


def _self_container_id() -> str:
    """Best-effort detection of the octop container's own ID.

    Used for ``--volumes-from`` so sandboxes inherit the octop-data volume
    (worktrees live inside it and are not reachable as host bind-mount paths).
    """
    # cgroup v2: /proc/self/cgroup contains "0::/docker/<id>" or similar.
    try:
        with open("/proc/self/cgroup", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if "docker" in line or "containerd" in line:
                    # last path segment is the container id
                    seg = line.rstrip("/").split("/")[-1]
                    if len(seg) >= 12:
                        return seg
    except OSError:
        pass
    # Fallback: hostname is the short container id by default.
    return socket.gethostname()


class RuntimeManager:
    def __init__(self, runtime_repo: RuntimeRepo) -> None:
        self._repo = runtime_repo
        self._client: docker.DockerClient | None = None
        self._self_id: str | None = None

    @property
    def client(self) -> docker.DockerClient:
        if self._client is None:
            self._client = docker.from_env()
        return self._client

    @property
    def self_container_id(self) -> str:
        if self._self_id is None:
            self._self_id = _self_container_id()
        return self._self_id

    def _container_name(self, session_id: str) -> str:
        return f"{CONTAINER_PREFIX}{session_id}"

    def create(
        self,
        *,
        session_id: str,
        image: str | None = None,
        cpus: float = DEFAULT_CPUS,
        memory: str = DEFAULT_MEMORY,
        pids_limit: int = DEFAULT_PIDS_LIMIT,
        allow_network: bool = True,
        worktree_path: str | None = None,
        runner: str | None = None,
        model: str | None = None,
        command: str | None = None,
    ) -> RuntimeRow:
        """Create a sandbox container for the session and record it.

        Returns the persisted runtime row. If a container already exists for
        the session it is reused. *command* (the runner's binary) is probed
        inside the image so a missing CLI is reported instead of timing out.
        """
        existing = self._repo.by_session(session_id)
        # A live/recently created row is reusable; a row left over from a
        # failed prestart (error/destroyed) must be recreated instead.
        if existing is not None and existing.status not in ("error", "destroyed", "stopped"):
            return existing

        runtime_id = f"rt_{uuid.uuid4().hex[:12]}"
        image = _sandbox_image(runner, image)
        self._repo.create(
            runtime_id=runtime_id,
            session_id=session_id,
            image=image,
            cpus=cpus,
            memory=memory,
            pids_limit=pids_limit,
            allow_network=allow_network,
            status="creating",
        )

        name = self._container_name(session_id)
        # Remove any stale container with the same name (leftover from crash).
        try:
            stale = self.client.containers.get(name)
            stale.remove(force=True)
        except docker.errors.NotFound:
            pass

        # Worktrees live inside the octop-data Docker volume, which is NOT a
        # host path — bind-mounting it into a sibling container resolves on the
        # host and yields an empty dir. Instead, inherit octop's volumes via
        # --volumes-from so the same volume (and thus the worktree) is visible
        # inside the sandbox at the identical path.
        volumes_from = [self.self_container_id]

        working_dir = SANDBOX_WORKDIR
        if worktree_path:
            os.makedirs(worktree_path, exist_ok=True)
            working_dir = worktree_path

        try:
            container = self.client.containers.run(
                image,
                command=["sleep", "infinity"],
                name=name,
                detach=True,
                nano_cpus=int(cpus * 1e9),
                mem_limit=memory,
                pids_limit=pids_limit,
                network_disabled=not allow_network,
                volumes_from=volumes_from,
                working_dir=working_dir,
                auto_remove=False,
            )
        except Exception:
            logger.exception("failed to create sandbox container for %s", session_id)
            self._repo.update_status(runtime_id, "error")
            raise

        # Point /workspace at the worktree so absolute paths emitted by the
        # coding CLI (e.g. "/workspace/foo.txt") land in the session worktree.
        if worktree_path and worktree_path != SANDBOX_WORKDIR:
            try:
                container.exec_run(
                    [
                        "sh",
                        "-c",
                        f"rm -rf {SANDBOX_WORKDIR} && ln -sfn {worktree_path} {SANDBOX_WORKDIR}",
                    ],
                    user="root",
                )
                # The worktree is created by octop (root); the sandbox runs as
                # the non-root 'agent' user, so it must own the worktree.
                container.exec_run(
                    ["sh", "-c", f"chown -R agent:agent {worktree_path}"],
                    user="root",
                )
            except Exception:  # noqa: BLE001 - non-fatal
                logger.exception("failed to prepare /workspace for %s", session_id)

        # A runner whose CLI is missing from the image later dies with an
        # opaque ACP handshake timeout; name the cause here instead.
        if command and self._probe_missing_command(container, command):
            logger.warning(
                "sandbox image %r does not provide %r required by runner %r; "
                "set %s%s to an image that ships it, or run unsandboxed",
                image,
                command,
                runner,
                _SANDBOX_IMAGE_ENV_PREFIX,
                (runner or "").upper().replace("-", "_"),
            )

        # Per-session model selection (S7): rewrite the runner's model config
        # inside the sandbox. Secrets are never part of these files.
        if runner and model:
            try:
                self._apply_model_config(container, runner=runner, model=model)
            except Exception:  # noqa: BLE001 - non-fatal, baked default stands
                logger.exception("failed to apply model %r for %s", model, session_id)

        self._repo.set_container(runtime_id, container.id)
        return self._repo.get(runtime_id)  # type: ignore[return-value]

    @staticmethod
    def _probe_missing_command(container: Container, command: str) -> bool:
        """True when *command* is not on PATH inside the sandbox.

        Best effort by design: an image without a shell, or any exec failure,
        reports "not missing" so this probe can never block a working setup.
        """
        if not command:
            return False
        try:
            _code, out = container.exec_run(
                ["sh", "-c", f"command -v {shlex.quote(command)} >/dev/null 2>&1 || echo missing"]
            )
        except Exception:  # noqa: BLE001 - diagnostic only
            return False
        return b"missing" in (out or b"")

    @staticmethod
    def _put_home_file(container: Container, path: str, content: str) -> None:
        """Write a file under /home/agent via docker-py (no shell quoting)."""
        buf = io.BytesIO()
        with tarfile.open(fileobj=buf, mode="w") as tar:
            info = tarfile.TarInfo(name=os.path.basename(path))
            data = content.encode("utf-8")
            info.size = len(data)
            info.mtime = int(time.time())
            info.uid = info.gid = 0
            tar.addfile(info, io.BytesIO(data))
        container.put_archive(os.path.dirname(path), buf.getvalue())
        # The sandbox 'agent' uid varies across images (999 here, 1000 in
        # others); chown by name so the runner can read/rewrite the file.
        container.exec_run(["chown", "agent:agent", path], user="root")

    def _apply_model_config(self, container: Container, *, runner: str, model: str) -> None:
        if not _MODEL_ID_RE.match(model):
            raise ValueError(f"invalid model id: {model!r}")
        if runner == "codex":
            self._put_home_file(
                container,
                "/home/agent/.codex/config.toml",
                _CODEX_CONFIG_TMPL.format(model=model),
            )
        elif runner == "opencode":
            self._put_home_file(
                container,
                "/home/agent/.config/opencode/opencode.json",
                json.dumps({"model": model}, ensure_ascii=False) + "\n",
            )
        # codebuddy (and env-driven runners) get the model via -e flags.

    def get_container(self, session_id: str) -> Container | None:
        try:
            return self.client.containers.get(self._container_name(session_id))
        except docker.errors.NotFound:
            return None

    def exec_command(self, session_id: str, cmd: list[str]) -> list[str]:
        """Return the argv to run *cmd* inside the session's sandbox.

        The harness spawns this as a subprocess; the docker CLI forwards
        stdin/stdout so the ACP stdio protocol works transparently.
        """
        return ["docker", "exec", "-i", self._container_name(session_id), *cmd]

    def health(self, session_id: str) -> bool:
        c = self.get_container(session_id)
        return c is not None and c.status == "running"

    def stop(self, session_id: str) -> None:
        c = self.get_container(session_id)
        if c is not None:
            try:
                c.stop(timeout=10)
            except Exception:
                logger.exception("stop sandbox failed for %s", session_id)
        row = self._repo.by_session(session_id)
        if row is not None:
            self._repo.update_status(row.runtime_id, "stopped")

    def destroy(self, session_id: str) -> None:
        c = self.get_container(session_id)
        if c is not None:
            try:
                c.remove(force=True)
            except Exception:
                logger.exception("destroy sandbox failed for %s", session_id)
        row = self._repo.by_session(session_id)
        if row is not None:
            self._repo.update_status(row.runtime_id, "destroyed")

    def logs(self, session_id: str, tail: int = 100) -> str:
        c = self.get_container(session_id)
        if c is None:
            return ""
        try:
            return c.logs(tail=tail).decode("utf-8", errors="replace")
        except Exception:
            return ""
