-- Schema v7: OIDC SSO providers, login states, and user identities.
CREATE TABLE IF NOT EXISTS sso_providers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0,
  display_name TEXT NOT NULL DEFAULT '',
  issuer TEXT NOT NULL DEFAULT '',
  client_id TEXT NOT NULL DEFAULT '',
  client_secret_enc BYTEA,
  scopes TEXT NOT NULL DEFAULT 'openid profile email',
  dashboard_origin TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sso_login_states (
  state TEXT PRIMARY KEY,
  provider_id INTEGER NOT NULL REFERENCES sso_providers(id) ON DELETE CASCADE,
  nonce TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  redirect_after TEXT NOT NULL DEFAULT '/chat',
  login_code TEXT,
  user_id INTEGER,
  expires_at INTEGER NOT NULL,
  consumed_at INTEGER,
  created_at INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sso_login_states_login_code
  ON sso_login_states(login_code) WHERE login_code IS NOT NULL;

ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sso_provider_id INTEGER REFERENCES sso_providers(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sso_subject TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email
  ON users(email) WHERE email IS NOT NULL AND email != '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_sso
  ON users(sso_provider_id, sso_subject)
  WHERE sso_provider_id IS NOT NULL AND sso_subject IS NOT NULL;

UPDATE _schema_version SET version = 7;
