-- Schema v16: coding sessions persistence (S3) — PostgreSQL dialect.
-- agent_events 跟随主库双方言，不强制 Postgres。
-- coding_runtimes / coding_worktrees / repositories / approval_requests 为
-- S4/S5/S6 预留表：本阶段只建表，不接 repo/业务代码。

CREATE TABLE IF NOT EXISTS coding_sessions (
  session_id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  runner TEXT NOT NULL,
  cwd TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready',
  turns BIGINT NOT NULL DEFAULT 0,
  acp_session_id TEXT,
  project_id TEXT,
  repository_id TEXT,
  branch TEXT,
  worktree_id TEXT,
  runtime_id TEXT,
  isolation_level TEXT,
  permission_policy TEXT,
  model_profile TEXT,
  trigger TEXT NOT NULL DEFAULT 'interactive',
  token_usage BIGINT NOT NULL DEFAULT 0,
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL,
  closed_at DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_coding_sessions_user
  ON coding_sessions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_coding_sessions_status
  ON coding_sessions (status);

CREATE TABLE IF NOT EXISTS agent_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  session_id TEXT NOT NULL,
  turn_id TEXT NOT NULL DEFAULT '',
  seq BIGINT NOT NULL,
  ts DOUBLE PRECISION NOT NULL,
  kind TEXT NOT NULL,
  is_error INTEGER NOT NULL DEFAULT 0,
  payload_json TEXT NOT NULL DEFAULT '{}',
  UNIQUE (session_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_agent_events_session_seq
  ON agent_events (session_id, seq);

CREATE TABLE IF NOT EXISTS coding_runtimes (
  runtime_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  image TEXT NOT NULL DEFAULT '',
  cpus DOUBLE PRECISION,
  memory TEXT,
  pids_limit BIGINT,
  allow_network INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'creating',
  container_id TEXT,
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_coding_runtimes_session
  ON coding_runtimes (session_id);

CREATE TABLE IF NOT EXISTS coding_worktrees (
  worktree_id TEXT PRIMARY KEY,
  repository_id TEXT,
  session_id TEXT NOT NULL,
  project_id TEXT,
  branch TEXT NOT NULL DEFAULT '',
  path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'creating',
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_coding_worktrees_session
  ON coding_worktrees (session_id);

CREATE TABLE IF NOT EXISTS repositories (
  repository_id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT '',
  provider TEXT NOT NULL DEFAULT '',
  default_branch TEXT NOT NULL DEFAULT 'main',
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_repositories_user
  ON repositories (user_id);

CREATE TABLE IF NOT EXISTS approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT NOT NULL UNIQUE,
  session_id TEXT NOT NULL,
  turn_id TEXT NOT NULL DEFAULT '',
  tool_name TEXT NOT NULL DEFAULT '',
  tool_kind TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  option_id TEXT,
  decided_by BIGINT,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at DOUBLE PRECISION NOT NULL,
  decided_at DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_approval_requests_session
  ON approval_requests (session_id, created_at DESC);

UPDATE _schema_version SET version = 16;
